FROM daocloud.io/library/php:7.1-fpm
#5.4.44-fpm

ADD debian.sources.list /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
#        libpng12-dev \
    && docker-php-ext-install iconv mcrypt bcmath mbstring \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install mysqli pdo_mysql

RUN pecl install swoole \
    && docker-php-ext-enable swoole

#Install redis extension
RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/3.0.0.tar.gz \
    && tar zxvf /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mkdir -p /usr/src/php/ext \
    && mv phpredis-3.0.0 /usr/src/php/ext/redis \
    && cd /usr/src/php/ext/redis \
    && docker-php-ext-install redis \
    && groupadd -g 1000 vboxsf \
    && usermod -a -G vboxsf www-data

ADD startup.sh /root/startup.sh
#RUN sh /root/startup.sh
#EXPOSE 8080
#CMD ["/root/default_entry.sh"]
CMD ["php-fpm"]
